# Generated by Django 5.1.5 on 2025-02-09 08:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="from_user",
        ),
        migrations.RemoveField(
            model_name="task",
            name="to_user",
        ),
        migrations.AddField(
            model_name="task",
            name="end_date",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="task",
            name="start_date",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
