version: '3.8'

services:
  web:
    build: .
    command: sh ./start.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - celery

  redis:
    image: "redis:latest"
    restart: always
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A authApi worker --loglevel=info
    depends_on:
      - redis
    volumes:
      - .:/app
