# Generated by Django 5.1.5 on 2025-01-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_logedin",
            field=models.BooleanField(default=True),
        ),
    ]
