# Generated by Django 5.1.5 on 2025-01-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_user_is_logedin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_logedin",
            field=models.BooleanField(default=False),
        ),
    ]
