# Generated by Django 5.1.5 on 2025-01-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_user_created_at_user_updated_at_userdevice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdevice",
            name="device_name",
            field=models.CharField(
                blank=True, default="Unknown Device", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="userdevice",
            name="device_type",
            field=models.CharField(default="Unknown Type", max_length=100),
        ),
    ]
