# Generated by Django 5.1.5 on 2025-02-09 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_alter_userdevice_device_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdevice",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="devices",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
