# Generated by Django 5.1.6 on 2025-02-26 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager_app", "0005_alter_task_priority_alter_task_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="permission",
            name="access_level",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="permission",
            name="action",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="permission",
            name="model",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[
                    ("very_high", "Very High"),
                    ("high", "High"),
                    ("medium", "Medium"),
                    ("low", "Low"),
                ],
                default="high",
                max_length=11,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("completed", "Completed"),
                    ("in_progress", "In Progress"),
                    ("pending", "Pending"),
                    ("not_started", "Not Started"),
                ],
                default="not_started",
                max_length=11,
            ),
        ),
        migrations.AlterField(
            model_name="userdevice",
            name="device_token",
            field=models.CharField(
                default="syFDQgu20VK5ylhundOM4ld2oIoKsPa1uwXHr6g5H56dTSpRjyAbS09iEspNZtXg",
                max_length=255,
                unique=True,
            ),
        ),
    ]
