# Generated by Django 5.1.6 on 2025-02-27 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "task_manager_app",
            "0008_rename_is_logedin_user_is_logged_in_user_parent_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[
                    ("very_high", "Very High"),
                    ("high", "High"),
                    ("medium", "Medium"),
                    ("low", "Low"),
                ],
                db_index=True,
                default="high",
                max_length=11,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("completed", "Completed"),
                    ("in_progress", "In Progress"),
                    ("pending", "Pending"),
                    ("not_started", "Not Started"),
                ],
                db_index=True,
                default="not_started",
                max_length=11,
            ),
        ),
        migrations.AlterField(
            model_name="userdevice",
            name="device_token",
            field=models.CharField(
                default="fs5u5tfW4ufukp07pdyLejpVw4xYbveCIF4uWawGFwMA00AGH3YQAnV5KQfgPQho",
                max_length=255,
                unique=True,
            ),
        ),
    ]
