# Generated by Django 5.1.6 on 2025-03-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager_app", "0013_alter_task_priority_alter_task_status_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userdevice",
            options={
                "ordering": ["is_active"],
                "verbose_name": "Device",
                "verbose_name_plural": "Devices",
            },
        ),
        migrations.RemoveField(
            model_name="user",
            name="full_name",
        ),
        migrations.RemoveField(
            model_name="userdevice",
            name="device_name",
        ),
        migrations.RemoveField(
            model_name="userdevice",
            name="device_type",
        ),
        migrations.AlterField(
            model_name="permission",
            name="id",
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="role",
            name="id",
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="rolepermission",
            name="id",
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="task",
            name="id",
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[
                    ("very_high", "Very High"),
                    ("high", "High"),
                    ("medium", "Medium"),
                    ("low", "Low"),
                ],
                db_index=True,
                default="high",
                max_length=11,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("completed", "Completed"),
                    ("in_progress", "In Progress"),
                    ("pending", "Pending"),
                    ("not_started", "Not Started"),
                ],
                db_index=True,
                default="not_started",
                max_length=11,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="userdevice",
            name="device_token",
            field=models.CharField(
                default="Dl36p6dMAMDTG28rfw6za0Z9Y4hvnrxdgz12GvauuX6E9S4U9sAzLCwZBXmSxfnL",
                max_length=255,
                unique=True,
            ),
        ),
    ]
