# Generated by Django 5.1.6 on 2025-03-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "task_manager_app",
            "0014_alter_userdevice_options_remove_user_full_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[
                    ("very_high", "Very High"),
                    ("high", "High"),
                    ("medium", "Medium"),
                    ("low", "Low"),
                ],
                db_index=True,
                default="high",
                max_length=11,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("completed", "Completed"),
                    ("in_progress", "In Progress"),
                    ("pending", "Pending"),
                    ("not_started", "Not Started"),
                ],
                db_index=True,
                default="not_started",
                max_length=11,
            ),
        ),
        migrations.AlterField(
            model_name="userdevice",
            name="device_token",
            field=models.CharField(
                default="euyFeju69Bvr8gMEv5souzH8A9tAFn1LB6IbDeBWbURG4A0djwDHZkQ5A21OVhyn",
                max_length=255,
                unique=True,
            ),
        ),
    ]
