# Generated by Django 5.1.6 on 2025-03-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "task_manager_app",
            "0025_rolepermission_description_alter_task_priority_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="rolepermission",
            name="description",
            field=models.TextField(default="No description", max_length=1000),
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[
                    ("very_high", "Very High"),
                    ("high", "High"),
                    ("medium", "Medium"),
                    ("low", "Low"),
                ],
                db_index=True,
                default="high",
                max_length=11,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("completed", "Completed"),
                    ("in_progress", "In Progress"),
                    ("pending", "Pending"),
                    ("not_started", "Not Started"),
                ],
                db_index=True,
                default="not_started",
                max_length=11,
            ),
        ),
        migrations.AlterField(
            model_name="userdevice",
            name="device_token",
            field=models.CharField(
                default="ol4Q18jDAUy74DEktk9uoWjT4UHKyW4GHJeL0mXk9ezfUJcqg49lsR2VsWqlXvFJ",
                max_length=255,
                unique=True,
            ),
        ),
    ]
